Подключение Vuex. Работа с глобальным состоянием приложения
htmlacademy-vue/635515-pizza-1 pull request #5
Opened 2022-01-14 20:12 UTC by Musisimaru

2022-04-08 00:05 UTC, enotke requested changes

2022-04-08 00:05 UTC, enotke commented on src/frontend/src/common/components/ItemCounter.vue
> +        oldCount,
А зачем ты везде тащишь этот oldCount. Он вроде бы не нужен особо

2022-04-08 00:05 UTC, enotke commented on src/frontend/src/modules/cart/CartAdditional.vue
> +        :isOrange="true"
Можно написать просто `<Counter isOrange>`

2022-04-08 00:05 UTC, enotke commented on src/frontend/src/store/modules/builder.store.js
> +  misc,
misc не используется

2022-04-08 00:05 UTC, enotke commented on src/frontend/src/store/modules/builder.store.js
> +  doughOptions: pizza.dough.map((doughItem) => extendDough(doughItem)),
Можно написать просто `pizza.dough.map(extendDough)`

2022-04-08 00:05 UTC, enotke commented on src/frontend/src/store/modules/cart.store.js
> +        state.pizza = [...state.pizza, { ...newPizza, id: increment++ }];
В качестве id лучше использовать timestamp

2022-04-08 00:05 UTC, enotke commented on src/frontend/src/common/helpers.js
> +  const filtered = positions.filter((pos) => pos.type === type);
Есть же метод find 

`return positions.find((pos) => pos.type === type) || null`

2022-04-08 21:35 UTC, Musisimaru commented on src/frontend/src/common/components/ItemCounter.vue
> +        oldCount,
Если это сейчас не нужно, то не значит, что не нужно будет в будущем. Компоненты надо писать как законченную полноценную запчасть. В данному случае это удобной шаблон ресивера на изменения значения, пригодится другому разработчику или мне в будущем. 

Такие мелочи экономят время и деньги команде

2022-04-08 21:36 UTC, Musisimaru commented on src/frontend/src/modules/cart/CartAdditional.vue
> +        :isOrange="true"
Огонь, спасибо

2022-04-08 21:36 UTC, Musisimaru commented on src/frontend/src/store/modules/builder.store.js
> +  misc,
действительно

2022-04-08 21:39 UTC, Musisimaru commented on src/frontend/src/common/helpers.js
> +  const filtered = positions.filter((pos) => pos.type === type);
Я старпёр, всё не привыкну, что это валиндный api. Спасибо.

2022-04-08 21:52 UTC, Musisimaru commented on src/frontend/src/store/modules/cart.store.js
> +        state.pizza = [...state.pizza, { ...newPizza, id: increment++ }];
Это чем? Тем, что имеет ненулевую вероятность повториться?

![html-academy_vue_hw05_demo-timestamp](https://user-images.githubusercontent.com/14264908/162536862-aa4e31ed-5caa-4da7-936e-deb34dc4c540.gif)

2022-04-09 05:38 UTC, enotke commented on src/frontend/src/store/modules/cart.store.js
> +        state.pizza = [...state.pizza, { ...newPizza, id: increment++ }];
Тем что переменную можно изменить. Timestamp это примитивный пример. Есть разные способы получить уникальное значение для ID.

2022-04-09 05:43 UTC, enotke commented on src/frontend/src/common/helpers.js
> +  const filtered = positions.filter((pos) => pos.type === type);
В целом код достаточно чистый и понятный. Единственное я бы немного по другому организовал механизм изменения позиций. Можно разделить изменяемые значения (количество ингредиентов, размер пиццы) и статические (список доступных ингредиентов, размеров и тд)

2022-04-09 05:43 UTC, merged

2022-04-09 05:44 UTC, enotke commented on src/frontend/src/common/components/ItemCounter.vue
> +        oldCount,
Не могу согласиться. Даже есть сформулированные правила. Не нужно изобретать велосипед и не нужно решать проблемы, которых нет и писать для этого сложные параметризованные функции «на будущее».